---
title: "Linear Model"
author: "Kate Culhane"
date: "February 12, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=5, fig.height=3, fig.align='center')
```


```{r packages and data, include=FALSE}

# Load necessary packages

library(tidyverse)
library(randomForest)

# Load necessary data

smamms <- read_csv('./data/unique_smamms.csv') # using dataset with one row per unique individual
effort <- read_csv('./data/effort.csv')

veg <- read_csv('./data/veg.csv') # csv created from vegetation variables calculated in '3_habitat.Rmd'

spatial <- read_csv('./data/spatial.csv') # csv created from fire severity spatial variables calculated in '4_spatial.Rmd'

diversity  <- read_csv('./data/diversity.csv') # csv created from diversity estimates calculated in '2_diversity_and_richness.Rmd'

```


```{r data wrangling, include=FALSE}

# Data wrangling

# Data for diversity GLM

dat_glm <- full_join(diversity, spatial) %>% 
  full_join(veg)

```


###GLM for diversity

```{r}

# Random forest to select variables

randomForest()

```



```{r glm}

# Build a GLM

smamm_glm <- glm(H ~ avg_severity + dist_to_edge + tree_survival, data = dat_glm)

smamm_glm


```

###Multivariate GLM for community composition
