---
title: "Spatial"
author: "Kate"
date: "January 7, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=5, fig.height=3, fig.align='center')
```


```{r packages and data, include=FALSE}

# Load necessary packages

library(tidyverse)
library(raster) # for raster work
library(rgdal) # for vector work (includes 'sp')
library(sf)
library(ggspatial)
library(mapview)
library(spatialEco) # for several landscape metrics
library(geosphere)

# Load necessary data

sites_dat <- read_csv('./data/spatial/sitecoords_all_10NOV2017.csv')

mtbs_info <- GDALinfo('./data/spatial/ca3878212060420140913_20130730_20150805_dnbr6.tif') # meta data for geotiff raster file from MTBS (burn severities)
mtbs_raster <- raster('./data/spatial/ca3878212060420140913_20130730_20150805_dnbr6.tif') # geotiff raster file from MTBS (burn severities)

bndy_shp <- read_sf(dsn = './data/spatial', layer = 'ca3878212060420140913_20130730_20150805_burn_bndy') # shapefile for burn boundary from MTBS

```


```{r data wrangling, include=FALSE}

# Vector shapefile for the site corners

corners_dat <- sites_dat %>% 
  filter(type == 'Plot Corner') %>% 
  mutate(northing = northing + 10000000)

corners_points <- corners_dat

coordinates(corners_points) <- ~ easting + northing

proj4string(corners_points) <- '+proj=utm +zone=10 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs' # CRS: WGS84 / UTM zone 10S

crs(mtbs_raster) # CRS for MTBS raster is NAD83 / AEA

corners_aea <- spTransform(corners_points, CRS('+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0
+datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 ')) # update site CRS to match mtbs CRS



# Vector shapefile for the site centroids

centers_dat <- corners_dat %>% 
  group_by(site) %>% 
  summarize(x = mean(easting), # average corner coords for centroid coords
            y = mean(northing))

site_points <- centers_dat

coordinates(site_points) <- ~ x + y

proj4string(site_points) <- '+proj=utm +zone=10 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs' # CRS: WGS84 / UTM zone 10S

sites_aea <- spTransform(site_points, CRS('+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0
+datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 ')) # update site CRS to match mtbs CRS


# Remove extra columns from burn boundary shapefile

bndy_poly <- bndy_shp %>% 
  dplyr::select(Fire_Name)

```


```{r echo=FALSE}

# Create polygons from site corner coords

corners_df <- as.data.frame(corners_aea)

sites_list <- list() # empty list to fill with polys for each site

for (i in unique(corners_df$site)) {
  df <- corners_df %>% 
    filter(site == i) %>% # filter for each site 
    dplyr::select(easting, northing) %>%
    rename(x = easting, y = northing)
  matrix <- base::as.matrix(df) # matrix with 1 col each for x, y
  poly <- Polygon(matrix) # create polygon object
  poly2 <- Polygons(list(poly), 1) # create multi-ring polygon object
  poly3 <- SpatialPolygons(list(poly2)) # create SpatialPolygon objecct
  proj4string(poly3) <-'+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 ' # update CRS
  assign(paste0(i, '_poly'), poly3) # assign each polygon a name
  sites_list[[i]] <- poly3 # add each SpatialPolygons object to a list
}

plot(mtbs_raster)

plot(sites_aea,
     col = 'blue',
     add = TRUE)

for (i in unique(corners_df$site)) {
  plot(sites_list[[i]],
       col = 'blue',
       add = TRUE)
}

```


```{r}

# Calculate average severity value for each site

site_pixels <- data.frame(site = character(), # blank data frame
                          severity = numeric())

for (i in unique(corners_df$site)) {
  df <- extract(mtbs_raster, sites_list[[i]], df = TRUE) %>% # extract pixel information within each site polygon
    mutate(site = i) %>% 
    rename(severity = ca3878212060420140913_20130730_20150805_dnbr6) %>% 
    dplyr::select(site, severity)
  site_pixels <- rbind(site_pixels, df) # add pixel information to df, one row per pixel
}

# Summary of number of pixels per severity at each site

pixel_summary <- site_pixels %>% 
  group_by(site, severity) %>% 
  summarize(length(severity))


```


```{r eval=FALSE, include=FALSE}

# Calculate distance to burn boundary

dist2Line(sites_aea, bndy_poly, distfun = distGeo) # DOESN'T WORK

```



```{r eval=FALSE, include=FALSE}

# Calculate landscape metrics

land.metrics(sites_aea, mtbs_raster,
             metrics = c('n.patches'), # metrics to calculate
             bw = 1000) # buffer distance




r <- raster(nrows=180, ncols=360, xmn=571823.6, xmx=616763.6, ymn=4423540,
ymx=4453690, resolution=270, crs = CRS("+proj=utm +zone=12 +datum=NAD83
+units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"))

r[] <- rpois(ncell(r), lambda=1)
r <- calc(r, fun=function(x) { x[x >= 1] <- 1; return(x) } )
x <- sampleRandom(r, 10, na.rm = TRUE, sp = TRUE)

lmet <- c("prop.landscape", "edge.density", "prop.like.adjacencies", "aggregation.index")
( class.1 <- land.metrics(x=x, y=r, bw=1000, bkgd = 0, metrics = lmet) )
( all.class <- land.metrics(x=x, y=r, bw=1000, bkgd = NA, metrics = lmet ) )

# Pull metrics associated with class "0"
all.class[["0"]]

```



Species dispersal ability

- Variablilty in home range


Spatial variables

- Distance to patch edge
- Patchiness