---
title: "Miscellaneous analyses"
author: "Kate"
date: "January 6, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=5, fig.height=3, fig.align='center')
```


```{r packages & data, include=FALSE}

# Load necessary packages

library(tidyverse)
library(fishmethods) # be careful, because this package depends on MASS and will override the dplyr 'select' function

# Load necessary data

smamms_all <- read_csv('./data/full_data.csv') # using full dataset with one row per capture
smamms <- read_csv('./data/unique_smamms.csv') # using dataset with one row per unique individual

```


```{r data wrangling, include=FALSE}

# Update classes

smamms <- smamms %>% 
  mutate(severity = factor(severity, levels = c('unb', 'mod', 'high')))

# Data frame containing only sites and severities

sevs <- smamms %>% 
  group_by(site) %>% 
  filter(row_number()==1) %>% 
  dplyr::select(site, severity) %>% 
  arrange(severity)

```

###Population size

```{r Schnabel estimate, include=FALSE}

# Calculating Schnabel's estimate of population size for each site

# Data wrangling

caps <- smamms_all %>% 
  dplyr::select(site, day, indID, recap) %>% 
  filter(!is.na(indID))

# Data frame of total abundance summed across all species at each site

abundance <- smamms %>% 
  group_by(site) %>% 
  summarize(length(species))

# Function that outputs a data frame with the vectors needed to calculate the Schnabel estimate
# Input is the site code

vectorify <- function(site_code) {
  caps %>% 
  filter(site == site_code) %>% 
  group_by(day, recap) %>% 
  summarize(n = length(indID)) %>% 
  spread(key = recap, value = n, fill = 0) %>% 
  mutate(catch = Y + N) %>% 
  rename(recaps = Y,
         newmarks = N)
}

# Calculate Schnabel's estimate for each site and create data frame of results

pop_est <- data.frame(site = factor(),
                      pop = numeric())

for (i in unique(smamms_all$site)) {
  schnabel_vecs <- vectorify(i)
  schnabel <- schnabel(catch = schnabel_vecs$catch,
              recaps = schnabel_vecs$recaps,
              newmarks = schnabel_vecs$newmarks)
  pop_est <- rbind(pop_est, data.frame(i, schnabel$N[1]))
}

# Combine abundance and Schnabel data frames

cap_rate <- full_join(pop_est, abundance, by = c('i' = 'site')) %>% 
  full_join(sevs, by = c('i' = 'site')) %>% 
  rename(site = i,
         schnabel = schnabel.N.1.,
         n = 'length(species)') %>% 
  mutate(cap_rate = n/schnabel)

```

**Population size across the fire severity gradient.** Population size, as calculated from the Schnabel estimate.

```{r Schnabel estimate boxplot, echo=FALSE}

# Boxplot of Schnabel estimate of population size by severity

colors <- c('darkgreen', 'orange', 'red')
xlabs <- c('Unburned', 'Moderate Severity', 'High Severity') 

schnabel_boxplot <- ggplot(cap_rate, aes(x = severity, y = schnabel)) +
  geom_boxplot(aes(fill = severity)) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  labs(x = 'Fire Severity',
       y = 'Population Size (N)') +
  theme(legend.position = 'NA') +
  scale_x_discrete(labels = xlabs)

schnabel_boxplot

```

**Capture rate at the three treatments.** Capture rate, calculated as the number of unique individuals captured divided by the Schnabel estimate of population size. All but three sites had a capture rate >75%.

```{r capture rate boxplot, echo=FALSE}

# Boxplot of capture rate by severity

caprate_boxplot <- ggplot(cap_rate, aes(x = severity, y = cap_rate)) +
  geom_boxplot(aes(fill = severity)) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  labs(x = 'Fire Severity',
       y = 'Capture Rate (%)') +
  theme(legend.position = 'NA') +
  scale_x_discrete(labels = xlabs)

caprate_boxplot

```

