---
title: "abundance"
author: "Kate"
date: "November 9, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages and data, include=FALSE}

# Load necessary packages
library(tidyverse)
library(dunn.test)

# Load necessary data
smamms <- read_csv('smamms.csv')
meta <- read_csv('sites.csv')

```


```{r simplified data frame}

# Create combined and simplified data frame with only unique animals
smammeta <- full_join(smamms, meta, by = c("site" = "site.code")) %>% 
  filter(species != 'MISS' & species != 'SPRU') %>% # remove SPRU and MISS
  group_by(indID) %>% 
  filter(row_number()==1) %>% # filter by unique animals
  ungroup() %>% 
  select(site, severity, species) %>% 
  mutate(
    severity = 
      case_when(
        severity == 'Green' ~ 'low',
        severity == 'Mixed' ~ 'med',
        severity == 'High' ~ 'high'
      )
  ) %>% 
  mutate(severity = factor(severity, levels = c('low', 'med', 'high')))

```


```{r total abundance}

# Calculate total abundance for all species at each site

abundance <- smammeta %>% 
  group_by(site) %>% 
  tally() %>% # count individuals per site
  full_join(., smammeta, by = 'site') %>% 
  select(site, severity, n) %>% 
  group_by(site) %>% 
  filter(row_number()==1) %>%
  ungroup()

```


```{r data distribution}

# Explore the data distribution

# Make histograms for each treatment
n_hist <- ggplot(abundance, aes(x = n)) +
  geom_histogram() +
  facet_wrap(~severity)

n_hist

# Make qqplots for each treatment
n_qq <- ggplot(abundance, aes(sample = n)) +
  geom_qq() +
  facet_wrap(~severity)

n_qq

# Histograms look a little funky because sample size is so small
# qq-plots look normal
# n=9 for each severity, so cannot use CLT to justify normality

```


```{r data variance}

# Explore variance
variances <- abundance %>% 
  group_by(severity) %>% 
  summarize(
    variance = var(n)
  )

variances

# Variances are WAY different (>4x)
# Cannot satisfy assumptions of ANOVA

```


```{r kruskal-wallis and post-hoc tests}

# Test for significant differences in means

# Kruskal Wallis
n_kw <- kruskal.test(n ~ severity, data = abundance)

n_kw

# p>0.05, so there are no sig differences in means

```


```{r boxplot}

# Summarize data with boxplots
colors <- c('darkgreen', 'orange', 'red')
xlabs <- c('Unburned', 'Mixed Severity', 'High Severity') 

n_boxplot <- ggplot(abundance, aes(x = severity, y = n)) +
  geom_boxplot(aes(fill = severity)) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  labs(x = 'Fire Severity',
       y = 'Total small mammal abundance') +
  theme(legend.position = 'NA') +
  scale_x_discrete(labels = xlabs)

n_boxplot

# Calculate mean diversity for each treatment

n_summary <- abundance %>% 
  group_by(severity) %>% 
  summarise(
    n_mean = mean(n),
    n_sd = sd(n)
  )

```


```{r PEMA abundance}

# Calculate total abundance for PEMA at each site

abundance_pema <- smammeta %>% 
  filter(species == 'PEMA') %>% 
  group_by(site) %>% 
  tally() %>% # count individuals per site
  full_join(., smammeta, by = 'site') %>% 
  select(site, severity, n) %>% 
  group_by(site) %>% 
  filter(row_number()==1) %>%
  ungroup()

```



```{r pema data distribution}

# Explore the data distribution

# Make histograms for each treatment
n_pema_hist <- ggplot(abundance_pema, aes(x = n)) +
  geom_histogram() +
  facet_wrap(~severity)

n_pema_hist

# Make qqplots for each treatment
n_pema_qq <- ggplot(abundance_pema, aes(sample = n)) +
  geom_qq() +
  facet_wrap(~severity)

n_pema_qq

# Histograms look a little funky because sample size is so small
# qq-plots look normal except high severity has a crazy outlier
# n=9 for each severity, so cannot use CLT to justify normality

```


```{r data variance}

# Explore variance
variances <- abundance_pema %>% 
  group_by(severity) %>% 
  summarize(
    variance = var(n)
  )

variances

# Variances are WAY different (>4x)
# Cannot satisfy assumptions of ANOVA

```


```{r kruskal-wallis and post-hoc tests}

# Test for significant differences in means

# Kruskal Wallis
n_pema_kw <- kruskal.test(n ~ severity, data = abundance_pema)

n_pema_kw

# p<0.05, so there is at least one sig difference in means

# Post-hoc pairwise testing

# Dunn's test
dunn.test(abundance_pema$n, abundance_pema$severity,
          method = 'bonferroni') # Bonferroni correction

# High severity is sig different from both unburned and mixed severity
# Unburned and mixed severity are not different from each other

```


```{r pema boxplot}

# Summarize data with boxplots
colors <- c('darkgreen', 'orange', 'red')
xlabs <- c('Unburned', 'Mixed Severity', 'High Severity') 

n_pema_boxplot <- ggplot(abundance_pema, aes(x = severity, y = n)) +
  geom_boxplot(aes(fill = severity)) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  labs(x = 'Fire Severity',
       y = 'Abundance (number of individuals)') +
  theme(legend.position = 'NA') +
  scale_x_discrete(labels = xlabs)

n_pema_boxplot

# Calculate mean diversity for each treatment

n_pema_summary <- abundance_pema %>% 
  group_by(severity) %>% 
  summarise(
    n_pema_mean = mean(n),
    n_pema_sd = sd(n)
  )

```


```{r PEMA proportion}

n_prop <- full_join(abundance, abundance_pema, by = 'site') %>% 
  select(site, severity.x, n.x, n.y) %>% 
  rename(severity = severity.x,
         n = n.x,
         n_pema = n.y) %>% 
  mutate(prop = n_pema/n) %>% 
  arrange(prop)

```


```{r prop data distribution}

# Explore the data distribution

# Make histograms for each treatment
n_prop_hist <- ggplot(n_prop, aes(x = prop)) +
  geom_histogram() +
  facet_wrap(~severity)

n_prop_hist

# Make qqplots for each treatment
n_prop_qq <- ggplot(n_prop, aes(sample = prop)) +
  geom_qq() +
  facet_wrap(~severity)

n_prop_qq

# Histograms look a little funky because sample size is so small
# qq-plots look sorta funky but maybe okay?
# n=9 for each severity, so cannot use CLT to justify normality

```


```{r prop data variance}

# Explore variance
variances <- n_prop %>% 
  group_by(severity) %>% 
  summarize(
    variance = var(prop)
  )

variances

# Variances are similar

```


```{r prop ANOVA and post-hoc tests}

# Test for significant differences in means

# ANOVA
prop_aov <- aov(prop ~ severity, data = n_prop)

summary(prop_aov)
# p<0.05, so there's at least one sig dif in means

# Post-hoc pairwise testing

# Tukey's HSD
prop_ph <- TukeyHSD(prop_aov)
prop_ph

# p=0.006 for low vs. high, but otherwise p>0.05
# significant difference between low and high severity means, but not between med vs. low or high severities

```


```{r prop boxplot}

# Summarize data with boxplots
colors <- c('darkgreen', 'orange', 'red')
xlabs <- c('Unburned', 'Mixed Severity', 'High Severity') 

n_prop_boxplot <- ggplot(n_prop, aes(x = severity, y = prop)) +
  geom_boxplot(aes(fill = severity)) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  labs(x = 'Fire Severity',
       y = 'Proportion of P. maniculatus') +
  theme(legend.position = 'NA') +
  scale_x_discrete(labels = xlabs)

n_prop_boxplot

# Calculate means for each treatment

n_prop_summary <- n_prop %>% 
  group_by(severity) %>% 
  summarise(
    n_prop_mean = mean(prop),
    n_prop_sd = sd(prop)
  )

```

