---
title: "rarefaction"
author: "Kate"
date: "November 7, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages and data, include=FALSE}

# Load necessary packages
library(tidyverse)
library(vegan)
library(iNEXT)

# Load necessary data
smamms <- read_csv('smamms.csv')
meta <- read_csv('sites.csv')

```


```{r simplified data frame}

# Create combined and simplified data frame with only unique animals
smammeta <- full_join(smamms, meta, by = c("site" = "site.code")) %>% 
  filter(species != 'MISS' & species != 'SPRU') %>% # remove SPRU and MISS
  group_by(indID) %>% 
  filter(row_number()==1) %>% # filter by unique animals
  ungroup() %>% 
  select(site, severity, species) %>% 
  mutate(
    severity = 
      case_when(
        severity == 'Green' ~ 'low',
        severity == 'Mixed' ~ 'med',
        severity == 'High' ~ 'high'
      )
  ) %>% 
  mutate(severity = factor(severity, levels = c('low', 'med', 'high')))

```


```{r species matrix, include=FALSE}

# Create a species matrix
matrix_temp <- smammeta %>% 
  group_by(site, species) %>% 
  tally() %>%  # count individuals per species per site
  spread(species, n) %>% # re-format into matrix
  ungroup() %>% 
  replace(., is.na(.), 0) # replace NAs with 0

matrix <- matrix_temp %>% 
  select(-site) # remove site column for input into vegan

sites <- matrix_temp$site # vector of just sites

row.names(matrix) <- sites # add sites to matrix as row names

# Create separate species matrices for each treatment

matrix_low <- matrix[1:9,] # species matrix for low severity
matrix_med <- matrix[19:27,] # species matrix for med severity
matrix_high <- matrix[10:18,] # species matrix for high severity

# Create species matrix by treatment

matrix_temp <- smammeta %>% 
  group_by(severity, species) %>% 
  tally() %>%  # count individuals per species per treatment
  spread(species, n) %>% # re-format into matrix
  ungroup() %>% 
  replace(., is.na(.), 0) # replace NAs with 0
  
matrix_sev <- matrix_temp %>% 
  select(-severity) # remove treatment column for input into vegan

treats <- matrix_temp$severity # vector of just treatments

row.names(matrix_sev) <- treats # add treatments to matrix as row names

```


```{r species accumulation}

# Species accumulation curves

accum_low <- specaccum(matrix_low, # low severity
                       method = 'rarefaction', 
                       permutations = 100)

accum_med <- specaccum(matrix_med, # medium severity
                       method = 'rarefaction',
                       permutations = 100)

accum_high <- specaccum(matrix_high, # high severity
                        method = 'rarefaction',
                        permutations = 100)

# Plot curves
plot(accum_low,
     ci = 2, # 95% confidence interval
     ci.type = 'polygon',
     ci.col = rgb(red=0, green=1, blue=0, alpha=0.25),
     ci.lty = 0,
     lwd = 2,
     col = 'darkgreen',
     xlab = 'Sites',
     ylab = 'Rarefaction')
lines(accum_med,
      ci = 2, # 95% confidence interval
      ci.type = 'polygon',
      ci.col = rgb(red=1, green=0.5, blue=0, alpha=0.25),
      ci.lty = 0,
      lwd = 2,
      col = 'orange')
lines(accum_high,
      ci = 2, # 95% confidence interval
      ci.type = 'polygon',
      ci.col = rgb(red=1, green=0, blue=0, alpha=0.25),
      ci.lty = 0,
      lwd = 2,
      col = 'red'
      )

```


```{r rarefaction}

# Calculate richness for each site using rarefaction
raremax <- min(rowSums(matrix))
raremax # minimum sample count = 5: rarefy using this value

rare <- rarefy(matrix, sample = raremax)

# Make a dataframe with site, severity, and H
richness <- data_frame(sites, rare) %>% 
  full_join(., smammeta, by = c('sites' = 'site')) %>% 
  select(sites, severity, rare) %>% 
  rename(site = sites) %>% 
  group_by(site) %>% 
  filter(row_number()==1)

```


```{r data distribution}

# Explore the data distribution

# Make histograms for each treatment
rare_hist <- ggplot(richness, aes(x = rare)) +
  geom_histogram() +
  facet_wrap(~severity)

rare_hist

# Make qqplots for each treatment
rare_qq <- ggplot(richness, aes(sample = rare)) +
  geom_qq() +
  facet_wrap(~severity)

rare_qq

# Histograms look a little funky because sample size is so small
# qq-plots for low and med severities look good, but qq-plot for high severity is skewed towards 0
# n=9 for each severity, so cannot use CLT to justify normality

```


```{r data variance}

# Explore variance
variances <- richness %>% 
  group_by(severity) %>% 
  summarize(
    variance = var(rare)
  )

variances

# The variances aren't that different for each severity

```


```{r ANOVA and post-hoc tests}

# Test for significant differences in means

# ANOVA
rare_aov <- aov(rare ~ severity, data = richness)

summary(rare_aov)
# p<0.05, so there's at least one sig dif in means

# Post-hoc pairwise testing

# Tukey's HSD
rare_ph <- TukeyHSD(rare_aov)
rare_ph

# p=0.003 for low vs. high, but otherwise p>0.05
# significant difference between low and high severity means, but not between med vs. low or high severities

```


```{r rarefaction per treatment}

# Calculate richness for each treatment using rarefaction
raremax2 <- min(rowSums(matrix_sev))
raremax2 # minimum sample count = 5: rarefy using this value

rare_sev <- rarefy(matrix_sev, sample = raremax2)

```


```{r rarefaction curves, echo=FALSE}

# Plot rarefaction curves for each site
curves <- rarecurve(matrix, sample = raremax, label = FALSE)

# Plot rarefaction curves for each treatment
colors <- c('darkgreen', 'orange', 'red')

curves_sev <- rarecurve(matrix_sev,
                        sample = raremax2,
                        col = colors,
                        lwd = 2,
                        label = FALSE)

iNEXT()

```
