---
title: "secr"
author: "Kate"
date: "November 9, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages and data, include=FALSE}

# Load necessary packages
library(tidyverse)
library(secr)
library(dunn.test)

# Load necessary data
smamms <- read_csv('smamms.csv')
trap <- read_csv("trapmatrix.csv")
meta <- read_csv('sites.csv')

```


Multi-session model:

- combine all sites into one model, with each 'session' consisting of  site
- add severity as a covariate
- add block as a covariate?
- create separate model for each species (starting with PEMA)
- account for variable trapping effort: SPRU or non-target capture = 0.5 usage; MISS = 1 usage


```{r create trap files}

# Data frame of sprung/missing traps and traps with non-PEMA captures
sprung_PEMA <- smamms %>% 
  filter(species != 'PEMA') %>%
  select(site, day, trap, species) %>% 
  mutate(usage = case_when(
    species == 'SPRU' ~ '0.5', # sprung traps coded as 0.5 usage
    species == 'MISS' ~ '0', # missing traps coded as 0 usage
    species != 'SPRU' & species != 'MISS' ~ '0.5' # non-target captures coded as 0.5 usage
  ))

# Function for creating a dataframe with a column for effort for each trap night, using a 'sprung' dataframe and trap night (day = 1,2,3)
det_effort <- function(x, night) {
  x %>% 
    filter(day == night) %>%
    full_join(trap, by = c('trap' = 'trapID')) %>% 
    arrange(trap) %>% 
    mutate(effort = case_when( # fill in remaining traps with usage = 1
      !is.na(usage) ~ usage,
      is.na(usage) ~ '1'
    )) %>% 
    select(trap, x, y, effort)
}

# Function for a creating trap dataframe with a column for effort over ALL trap nights at a specific site, using the 'sprung_PEMA' dataframe and and a site
# Requires the det_effort function
sprungify <- function(x, site_code) {
  sprung_site <- x %>% filter(site == site_code)
  
  sprung1 <- det_effort(sprung_site, 1)
  sprung2 <- det_effort(sprung_site, 2)
  sprung3 <- det_effort(sprung_site, 3)
  
  sprung_all <- full_join(sprung1, sprung2,
                          by = c('trap', 'x', 'y')) %>% 
    full_join(sprung3, by = c('trap', 'x', 'y')) %>% 
    mutate(effort = paste(effort.x, effort.y, effort, # create column with strings of effort over all three trap nights
                          sep = ' ')) %>% 
    select(trap, x, y, effort)
} 

# Create CSV files for each session (i.e. site)
for (i in meta$site.code) {
  sprung_all <- sprungify(sprung_PEMA, site_code = i)
  write_csv(sprung_all, paste0('trapfile.', i, '.csv'), col_names = FALSE)
}

```


```{r create capture file}

# Create dataframe of all PEMA captures for all sessions
capt <- smamms %>% 
  filter(!is.na(indID))%>% # captures only
  mutate(occassion = ifelse( # adding a - for animals that died on capture
           is.na(catnum), day, paste0('-', day)
           )) %>% 
  filter(species=='PEMA') %>%
  select(site, indID, occassion, trap) %>% 
  rename(session = site,
         ID = indID,
         detector = trap)

capt$detector <- as.factor(capt$detector)

capt <- as.data.frame(capt)

# Create CSV file for all sessions
write_csv(capt,'smamms_capt.csv', col_names = FALSE)

```


```{r create capture history object}

# Create a vector of the trap files for all sessions
trapfiles <- c('trapfile.GRNHOU.csv', 'trapfile.GRNMAS.csv', 'trapfile.GRNTUR.csv', 
               'trapfile.GRNCAR.csv', 'trapfile.GRNKAN.csv', 'trapfile.GRNWOO.csv', 
               'trapfile.GRNDAM.csv', 'trapfile.GRNQUA.csv', 'trapfile.GRNSNO.csv', 
               'trapfile.MIXBUS.csv', 'trapfile.MIXMIX.csv', 'trapfile.MIXMOR.csv', 
               'trapfile.MIXDP2.csv', 'trapfile.MIXMID.csv', 'trapfile.MIXRAV.csv', 
               'trapfile.MIXBUT.csv', 'trapfile.MIXRIV.csv', 'trapfile.MIXWAT.csv', 
               'trapfile.HICORN.csv', 'trapfile.HIDODD.csv', 'trapfile.HITEDD.csv', 
               'trapfile.HICOWS.csv', 'trapfile.HISQUE.csv', 'trapfile.HIWALK.csv', 
               'trapfile.HIBADR.csv', 'trapfile.HICAMP.csv', 'trapfile.HISHRU.csv')

# Use read.capthist to make a capture history object

smammCH <- read.capthist('smamms_capt.csv', trapfiles,
                         detector = 'multi',
                         fmt = 'trapID',
                         noccasions = 3,
                         binary.usage = FALSE)

```



```{r create files}

# Create trap file

# Data frame of sprung/missing traps
sprung <- smamms %>% 
  filter(species == 'SPRU' | species == 'MISS') %>%
  select(site, day, trap, species) %>% 
  mutate(usage = case_when(
    species == 'SPRU' ~ '0.5',
    species == 'MISS' ~ '0'
  ))

# Data frame of sprung/missing traps, plus traps with non-PEMA captures
sprung_PEMA <- smamms %>% 
  filter(species != 'PEMA') %>%
  select(site, day, trap, species) %>% 
  mutate(usage = case_when(
    species == 'SPRU' ~ '0.5',
    species == 'MISS' ~ '0',
    species != 'SPRU' & species != 'MISS' ~ '0.5'
  ))

det_effort <- function(x, session) {
  x %>% 
    filter(day == session) %>% 
    full_join(trap, by = c('trap' = 'trapID')) %>% 
    arrange(trap) %>% 
    mutate(effort = case_when(
      !is.na(usage) ~ usage,
      is.na(usage) ~ '1'
    )) %>% 
    select(trap, x, y, effort)
} # function for creating vector of effort for each session

sprungify <- function(x, site_code) {
  sprung_site <- x %>% filter(site == site_code)
  
  sprung1 <- det_effort(sprung_site, 1)
  sprung2 <- det_effort(sprung_site, 2)
  sprung3 <- det_effort(sprung_site, 3)
  
  sprung_all <- full_join(sprung1, sprung2,
                          by = c('trap', 'x', 'y')) %>% 
    full_join(sprung3, by = c('trap', 'x', 'y')) %>% 
    mutate(effort = paste(effort.x, effort.y, effort,
                          sep = ' ')) %>% 
    select(trap, x, y, effort)
} # function for creating trap data frame using the 'sprung' data frame and and the site

sprungify(sprung_PEMA, site_code = 'MIXRIV')
write_csv(sprung_all, 'smamms_trap.csv', col_names = FALSE)

# Create capture file

captify <- function(x, site_code, species_code) {
  capt <- x %>% 
    filter(!is.na(indID))%>% # captures only
    mutate(session = as.factor(paste0(site, '-', species)),
           occassion = ifelse(
             is.na(catnum), day, paste0('-', day)
             )) %>% # adding a - for animals that died on capture
    filter(species==species_code) %>%
    filter(site==site_code) %>%
    select(session, indID, occassion, trap) %>% 
    rename(session = session,
           ID = indID,
           detector = trap)
 
   capt$detector <- as.factor(capt$detector)
  
  capt <- as.data.frame(capt)
  
  write_csv(capt,'smamms_capt.csv', col_names = FALSE)
} # function for creating capture history file using the 'smamms' data frame, the site, and the species

captify(smamms, site_code = 'MIXWAT', species_code = 'PEMA')

# Create capture history object

smammCH <- read.capthist('smamms_capt.csv', 'smamms_trap.csv',
                         detector = 'multi',
                         fmt = 'trapID',
                         noccasions = 3,
                         binary.usage = FALSE)

```


```{r multi-session}

# Create a trap file for each session

sprungify(sprung_PEMA, site_code = 'GRNCAR')

write_csv(trap, 'traps.GRNCAR.csv', col_names = FALSE)

# Create capture file 

capt <- smamms %>% 
  filter(!is.na(indID))%>% # captures only
  mutate(session = as.factor(paste0(site, '-', species)),
         occassion = ifelse(
           is.na(catnum), day, paste0('-', day)
           )) %>% # adding a - for animals that died on capture
  filter(species=='PEMA') %>%
  select(site, indID, occassion, trap) %>% 
  rename(session = site,
         ID = indID,
         detector = trap)

capt$detector <- as.factor(capt$detector)

capt <- as.data.frame(capt)

write_csv(capt,'smamms_capt.csv', col_names = FALSE)

# Create capture history object

smammCH <- read.capthist('smamms_capt.csv', c('smamms_trap.csv'),
                         detector = 'multi',
                         fmt = 'trapID',
                         noccasions = 3,
                         binary.usage = FALSE)

```

```{r summary}

# Summary
summary(smammCH)

# Plot
par(mar = c(1,1,3,1)) # reduce margins
plot(smammCH, tracks=TRUE)

# Histogram of movement distance
m <- unlist(moves(smammCH))
par(mar = c(3.2,4,1,1), mgp = c(2.1,0.6,0)) # reduce margins
hist(m, xlab = "Movement m", main = "")

```


```{r basic model}

# Test a basic model
initialsigma <- RPSV(smammCH, CC = TRUE) # quick and biased estimate of sigma

fit <- secr.fit(smammCH,
                buffer = 4 * initialsigma, # unlikely that PEMA will go outside this parameter
                trace = FALSE)

fit # D in the last table is the estimated density

```


```{r comparing models}

# Compare three models

# Half-normal
fit_HN <- secr.fit (smammCH, buffer = 6 * initialsigma, detectfn = 'HN', trace = FALSE)

# Negative exponential
fit_EX <- secr.fit (smammCH, buffer = 6 * initialsigma, detectfn = 'EX', trace = FALSE)

# Hazard rate
fit_HR <- secr.fit (smammCH, buffer = 6 * initialsigma, detectfn = 'HR', trace = FALSE)

# Bundle and compare models
fits <- secrlist(HN = fit_HN, EX = fit_EX, HR = fit_HR)

predict(fits) # similar estimates of D except for HR (underestimating)

AIC(fits) # formal model comparison: 1) HR, 2) EX, 3) HN

par(mar = c(4,4,2,2))
esa.plot(fits, max.buffer = 6 * initialsigma) # HR doesn't plateau as much as EX and HN --> estimates are more affected by buffer width

# Use EX model (negative exponential)
fit_EX

param <- derived(fit_EX)
param$estimate[2] # estimated density

```

```{r RUN FOR EACH SITE}

# Condensed code: run for each site separately to get density estimate

# Create capture file
capt<-smamms %>%
  mutate(session = as.factor(paste0(site, '-', species)), 
         occassion = ifelse(is.na(catnum), day, paste0('-', day))) %>% 
  filter(species=='PEMA') %>% 
  filter(site=='MIXWAT') %>% # CHANGE SITE HERE
  select(session, indID, occassion, trap) %>% 
  rename(session = session,
         ID = indID,
         detector = trap)
capt$detector <- as.factor(capt$detector)
capt <- as.data.frame(capt)
write_csv(capt,'smamms_capt.csv', col_names = FALSE) 
# Create capture history object
smammCH <- read.capthist('smamms_capt.csv', 'smamms_trap.csv',
                         detector = 'multi',
                         fmt = 'trapID',
                         noccasions = 3)
initialsigma <- RPSV(smammCH, CC = TRUE)
# Negative exponential model
fit_EX <- secr.fit (smammC,
                    buffer = 6 * initialsigma, detectfn = 'EX', trace = FALSE)
param <- derived(fit_EX)
param$estimate[2]



```


```{r data frame of densities}

densities <- c(0.6453089, 4.800268, 4.051649,
               5.908946, 3.812545, 8.822407,
               8.649417, 8.121382, 5.749518,
               13.71822, 1.363503, 1.120058,
               4.429102, 3.835955, 16.45039,
               2.958632, 3.321139, 0.5888588,
               21.37639, 12.19324, 44.1339,
               6.394768, 18.75583, 12.69593,
               9.028069, 16.74234, 10.95847)

sites <- c('GRNCAR', 'GRNDAM', 'GRNHOU',
           'GRNKAN', 'GRNMAS', 'GRNQUA',
           'GRNSNO', 'GRNTUR', 'GRNWOO',
           'MIXBUS', 'MIXBUT', 'MIXDP2',
           'MIXMID', 'MIXMIX', 'MIXMOR',
           'MIXRAV', 'MIXRIV', 'MIXWAT',
           'HIBADR', 'HICAMP', 'HICORN',
           'HICOWS', 'HIDODD', 'HISHRU',
           'HISQUE', 'HITEDD', 'HIWALK')

sevs <- c(rep('low',9), rep('med', 9), rep('high', 9))

density <- data_frame(sites, sevs, densities) %>% 
  rename(
    site = sites,
    severity = sevs,
    D = densities
  )
density$severity <- factor(density$severity, levels = c('low', 'med', 'high'))

```


```{r data distribution}

# Explore the data distribution

# Make histograms for each treatment
D_hist <- ggplot(density, aes(x = D)) +
  geom_histogram() +
  facet_wrap(~severity)

D_hist

# Make qqplots for each treatment
D_qq <- ggplot(density, aes(sample = D)) +
  geom_qq() +
  facet_wrap(~severity)

D_qq

# Histograms look a little funky because sample size is so small
# qq-plots are weird???
# n=9 for each severity, so cannot use CLT to justify normality

```


```{r data variance}

# Explore variance
variances <- density %>% 
  group_by(severity) %>% 
  summarize(
    variance = var(D)
  )

variances

# The variances are WAY different
# Cannot satisfy assumptions of ANOVA

```


```{r kruskal-wallis and post-hoc tests}

# Test for significant differences in means

# Kruskal Wallis

D_kw <- kruskal.test(D ~ severity, data = density)

D_kw
# p<0.05, so there is at least 1 sig dif in means

# Post-hoc pairwise testing

# Dunn's test
dunn.test(density$D, density$severity,
          method = 'bonferroni') # Bonferroni correction

# High severity is sig different from both unburned and mixed severity
# Unburned and mixed severity are not different from each other

```


```{r boxplot}

# Summarize data with boxplots
colors <- c('darkgreen', 'orange', 'red')
xlabs <- c('Unburned', 'Mixed Severity', 'High Severity') 

H_boxplot <- ggplot(density, aes(x = severity, y = D)) +
  geom_boxplot(aes(fill = severity)) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  labs(x = 'Fire Severity',
       y = substitute(paste(
         italic('P. maniculatus'), " density (indv/ha)"
         ))) +
  theme(legend.position = 'NA') +
  scale_x_discrete(labels = xlabs)

H_boxplot

# Calculate mean density for each treatment

D_summary <- density %>% 
  group_by(severity) %>% 
  summarise(
    D_mean = mean(D),
    D_sd = sd(D)
  )

```


```{r automate for each site, eval=FALSE, include=FALSE}

# Create trap file
trap1 <- trap %>% 
  rename(detector = trapID)
trapf<-read.traps(data = trap1, detector = "multi", trapID = 'detector')
# NEED CODE TO ADD TRAPPING EFFORT, site == i
write_csv(trap1,'smamms_trap.csv', col_names = FALSE)

# Create capture file
capt<-smamms %>%
  filter(!is.na(indID))%>% # captures only
  mutate(session = as.factor(paste0(site, '-', species)),
         occassion = ifelse(is.na(catnum), day, paste0('-', day))) %>%
  filter(species=='PEMA') %>%
  filter(site==i) %>% 
  select(session, indID, occassion, trap) %>% 
  rename(session = session,
         ID = indID,
         detector = trap)
capt$detector <- as.factor(capt$detector)
capt <- as.data.frame(capt)
write_csv(capt,'smamms_capt.csv', col_names = FALSE)

# Create capture history object
smammCH <- read.capthist('smamms_capt.csv', 'smamms_trap.csv',
                         detector = 'multi',
                         fmt = 'trapID',
                         noccasions = 3)

```


