---
title: "summary"
author: "Kate"
date: "November 11, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages & data, include=FALSE}

# Load necessary packages
library(tidyverse)
library(kableExtra)

# Load necessary data
smamms <- read_csv('smamms.csv')
meta <- read_csv('sites.csv')
spp_info <- read_csv('species_info.csv')

```


```{r simplified data frames, include=FALSE}

# Create severity dataframe
sevs <- meta %>% 
    mutate(
    severity = 
      case_when(
        severity == 'Green' ~ 'low',
        severity == 'Mixed' ~ 'med',
        severity == 'High' ~ 'high'
      )
  ) %>% 
  mutate(severity = factor(severity, levels = c('low', 'med', 'high'))) %>% 
  rename(site = site.code) %>% 
  arrange(severity) %>% 
  select(site, severity)

# Create combined and simplified data frame with only unique animals
smammeta <- full_join(smamms, sevs, by = 'site') %>% 
  filter(species != 'MISS' & species != 'SPRU') %>%
  group_by(indID) %>% 
  filter(row_number()==1) %>% # filter by unique animals
  ungroup() %>% 
  select(site, severity, species)

# Create species dataframe with shortened binomials
spp_names <- spp_info %>% 
  mutate(binomial_short = paste0(
    substring(binomial,1,1),
    ". ",
    gsub(".* ", '', binomial)
  )) %>% 
  select(family, species, common_name, binomial, binomial_short)

```


```{r trapping effort, echo=FALSE}

# Data frame of trapping effort at each site
effort <- smamms %>% 
  filter(species == 'SPRU' | species == 'MISS') %>%
  select(site, day, trap, species) %>% 
  mutate(usage = case_when(
    species == 'SPRU' ~ 0.5, # sprung traps coded as 0.5 usage
    species == 'MISS' ~ 1 # missing traps coded as 1 usage (to be subtracted)
  )) %>% 
  group_by(site) %>% 
  summarize(sprung = sum(usage)) %>% 
  mutate(effort = 300 - sprung) %>% 
  select(site, effort)

# Summary of overall mammal abundances
summary <- smammeta %>% 
  group_by(species) %>% 
  summarize(n = length(species)) %>% 
  full_join(spp_names, by = 'species') %>% 
  filter(!is.na(n)) %>% 
  select(family, binomial, common_name, n) %>% 
  arrange(family)

cols = c('Family', 'Common Name', 'Binomial', 'Individuals')

summary_table <- kable(summary,
                       col.names = cols) %>% 
  kable_styling(bootstrap_options = c('striped', 'condensed'),
                full_width = FALSE) %>% 
  column_spec(1, width = '3cm') %>% 
  column_spec(2, italic = TRUE) %>% 
  column_spec(4, width = '2cm')

summary_table

```


```{r proportional abundance per site}

# Dataframe of proportional species abundance per site
prop_site <- smammeta %>% 
  group_by(site, species) %>% 
  summarize(n = length(species)) %>% 
  mutate(prop = n/sum(n))

# Column graph of proportional species abundance per site
prop_site_fig <- ggplot(prop_site, aes(x = site, y = prop,
                                       fill = species)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

prop_site_fig

```


```{r proportional abundance per species}

# Dataframe of proportional treatment abundances per species
prop_species <- smammeta %>% 
  group_by(species, site) %>% 
  summarize(n = length(site)) %>% 
  full_join(effort, by = 'site') %>% 
  mutate(cpue = n/effort * 300) %>% # adjust for trapping effort
  full_join(sevs, by = 'site') %>% 
  group_by(species, severity) %>% 
  summarize(n = sum(cpue)) %>% 
  mutate(prop = n/sum(n)*100) %>% # proportion of captures at each treatment, per species
  left_join(spp_names, by = 'species')

prop_high <- prop_species %>% 
  filter(severity == 'high') %>% 
  select(species, prop) %>% 
  rename(prop_high = prop)
prop_med <- prop_species %>% 
  filter(severity == 'med') %>% 
  select(species, prop) %>% 
  rename(prop_med = prop)

prop_species2 <- prop_species %>% 
  full_join(prop_high, by = 'species') %>% 
  full_join(prop_med, by = 'species') %>% 
  mutate(
    prop_high = case_when(
      is.na(prop_high) ~ 0,
      !is.na(prop_high) ~ prop_high
    ),
    prop_med = case_when(
      is.na(prop_med) ~ 0,
      !is.na(prop_med) ~ prop_med
    )
  ) %>% 
  ungroup() %>% 
  mutate(binomial_short = as_factor(binomial_short),
         binomial_short = fct_reorder(binomial_short, prop_med),
         binomial_short = fct_reorder(binomial_short, prop_high))

# Column graph of proportional treatment abundances per species

colors <- c('darkgreen', 'orange', 'red')
labs <- c('Unburned', 'Mixed', 'High')

prop_species_fig <- ggplot(prop_species2,
                           aes(x = binomial_short,
                               y = prop,
                               fill = severity)) +
  geom_col() +
  scale_fill_manual(values = colors,
                    name = 'Fire severity',
                    labels = labs) +
  coord_flip() +
  scale_y_continuous(breaks = c(0, 50, 100)) +
  theme_minimal() +
  labs(x = '',
       y = 'Occurence by fire severity (%)') +
  theme(axis.text.y = element_text(face = 'italic'))

prop_species_fig

```

Questions about standardizing per effort...

- Standardize by traps sprung by "non-target" species for every species?
- How to standardize by effort when we're only counting unique individuals, not total captures? (e.g. incorporate cpue into mark-recap?)


