---
title: "Summary Figure"
author: "Kate Culhane"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = '..')
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.width=5, fig.height=3)
```

<br>

```{r packages & data}

# Load packages

library(tidyverse)
library(ggnewscale)
library(scales)
library(ggthemes)
library(cowplot) # plot_grid function

# Load data

abundance <- read_csv('output_data/abundance.csv')
diversity <- read_csv('output_data/diversity.csv')
FD <- read_csv('output_data/FD_biomass.csv')
PD <- read_csv('output_data/PD.csv')

colors <- c('darkgreen', 'orange', 'red')
sevs <- c('Unburned', 'Low-Mod\nSeverity', 'High\nSeverity')

```

```{r}

# Combined data frame
metrics <- full_join(abundance, FD) %>% 
  full_join(diversity) %>% 
  full_join(PD) %>% 
  mutate(severity = factor(severity, levels = c('unb', 'mod', 'high')),
         biomass = biomass_total/1000) %>% 
    select(site, severity,
           n_adj, biomass, n_adj_pema, n_adj_sotr,
           rarefied_richness, J, FEve, PD)

# Summary data frame 
summary <- metrics %>% 
  gather(key = 'metric', value = 'value', 3:10) %>% 
  group_by(metric, severity) %>% 
  summarize(mean = mean(value, na.rm = TRUE),
            se = sd(value, na.rm = TRUE)/sqrt(length(value))) %>% 
  ungroup() %>% 
  mutate(metric = factor(metric, levels = c('n_adj', 'biomass',
                                            'n_adj_pema', 'n_adj_sotr',
                                            'rarefied_richness', 'J',
                                            'FEve', 'PD')))

# Vectors
metric_labs <- c('Total abundance\n(indv/site)', 'Biomass\n(kg/site)',
              'Deer mouse\nabundance (indv/site)', 'Trowbridge\'s shrew\nabundance (indv/site)',
              'Rarefied\nrichness', 'Evenness',
              'FEve', 'Faith\'s PD')
names(metric_labs) <- c('n_adj', 'biomass', 'n_adj_pema', 'n_adj_sotr',
                        'rarefied_richness', 'J', 'FEve', 'PD')

```

### Summary Figure: abundance/biomass

```{r}

summary %>% 
  filter(metric=='n_adj' | metric=='biomass' | metric=='n_adj_pema' | metric=='n_adj_sotr') %>% 
  ggplot() +
  geom_col(aes(x = severity, y = mean, fill = severity)) +
  geom_errorbar(aes(x = severity, ymin = mean-se, ymax = mean+se),
                width = 0.2) +
  scale_fill_manual(values = c('darkgreen', 'orange', 'red')) +
  theme_void() +
  theme(legend.position = 'NA',
        axis.line.y = element_line(),
        axis.line.x = element_line(),
        axis.text.y = element_text(size = 8),
        strip.text = element_text(size = 9, angle = 270, vjust = 1),
        strip.placement = 'outside',
        plot.margin = unit(c(10,10,10,10), 'pt'),
        panel.spacing.x = unit(20, 'pt'),
        panel.spacing.y = unit(30, 'pt')) +
  scale_y_continuous(breaks = pretty_breaks(3),
                     expand = c(0,0)) +
  facet_wrap(~metric, ncol = 2, dir = 'h', scales = 'free',
             strip.position = 'left',
             labeller = labeller(metric = metric_labs))

```

```{r}

set.seed(2)
abun_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=n_adj, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=n_adj), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9),
        axis.text.x = element_blank()) +
  scale_y_continuous(limits=c(0,60), expand=c(0,0), breaks=c(0,20,40,60)) +
  labs(x='', y='Total abundance\n(indv/site)')

set.seed(5)
biomass_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=biomass, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=biomass), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9),
        axis.text.x = element_blank()) +
  scale_y_continuous(limits=c(0,3.1), expand=c(0,0), breaks=c(0,1,2,3)) +
  labs(x='', y='Biomass\n(kg/site)')

set.seed(2)
pema_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=n_adj_pema, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=n_adj_pema), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9)) +
  scale_y_continuous(limits=c(0,60), expand=c(0,0), breaks=c(0,20,40,60)) +
  scale_x_discrete(labels=sevs) +
  labs(x='', y='Deer mouse\nabundance (indv/site)')

set.seed(13)
sotr_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=n_adj_sotr, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=n_adj_sotr), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9)) +
  scale_y_continuous(limits=c(0,7), expand=c(0,0), breaks=c(0,2,4,6)) +
  scale_x_discrete(labels=sevs) +
  labs(x='', y='Trowbridge\'s shrew\nabundance (indv/site)')

plot_grid(abun_plot, biomass_plot, pema_plot, sotr_plot,
          ncol = 2, align = 'v',
          rel_heights = c(1, 1, 1.1, 1.1))

ggsave('figs/fig2.png', plot = last_plot(),
       width = 5.5, height = 4, units = 'in')
```

<br>

### Summary Figure: diversity

```{r}

summary %>% 
  filter(metric=='rarefied_richness' | metric=='J' | metric=='FEve' | metric=='PD') %>% 
  ggplot() +
  geom_col(aes(x = severity, y = mean, fill = severity)) +
  geom_errorbar(aes(x = severity, ymin = mean-se, ymax = mean+se),
                width = 0.2) +
  scale_fill_manual(values = c('darkgreen', 'orange', 'red')) +
  theme_void() +
  theme(legend.position = 'NA',
        axis.line.y = element_line(),
        axis.line.x = element_line(),
        axis.text.y = element_text(size = 9),
        strip.text = element_text(size = 10, angle = 270),
        strip.placement = 'outside',
        plot.margin = unit(c(10,10,10,10), 'pt'),
        panel.spacing.x = unit(20, 'pt'),
        panel.spacing.y = unit(25, 'pt')) +
  scale_y_continuous(breaks = pretty_breaks(3),
                     expand = c(0,0)) +
  facet_wrap(~metric, ncol = 2, dir = 'h', scales = 'free',
             strip.position = 'left',
             labeller = labeller(metric = metric_labs))

ggsave('figs/fig3.png', plot = last_plot(),
       width = 4, height = 3.5, units = 'in')

```

```{r}

set.seed(24)
rich_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=rarefied_richness, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=rarefied_richness), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9),
        axis.text.x = element_blank()) +
  scale_y_continuous(limits=c(0,3.3), expand=c(0,0), breaks=c(0,1,2,3)) +
  labs(x='', y='Rarefied richness')

set.seed(6)
even_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=J, color=severity), width=0.1, size=1.5, na.rm=TRUE) +
  geom_boxplot(aes(x=severity, y=J), fill=NA, outlier.shape=NA, na.rm=TRUE) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9),
        axis.text.x = element_blank()) +
  scale_y_continuous(limits=c(0,1.1), expand=c(0,0), breaks=c(0,1,2,3)) +
  labs(x='', y='Pielou\'s evenness')

set.seed(8)
function_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=FEve, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=FEve), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9)) +
  scale_y_continuous(limits=c(0,1), expand=c(0,0), breaks=c(0,0.5,1)) +
  scale_x_discrete(labels=sevs) +
  labs(x='', y='FEve')

set.seed(13)
phylo_plot <- metrics %>% 
  ggplot() +
  geom_jitter(aes(x=severity, y=PD, color=severity), width=0.1, size=1.5) +
  geom_boxplot(aes(x=severity, y=PD), fill=NA, outlier.shape=NA) +
  scale_color_manual(values=colors) +
  theme_classic() +
  theme(legend.position = 'NA',
        axis.text.y = element_text(size = 9)) +
  scale_y_continuous(limits=c(0,300), expand=c(0,0), breaks=c(0,100,200,300)) +
  scale_x_discrete(labels=sevs) +
  labs(x='', y=' Faith\'s PD')

plot_grid(rich_plot, even_plot, function_plot, phylo_plot,
          ncol = 2, align = 'v',
          rel_heights = c(1, 1, 1.1, 1.1))

ggsave('figs/fig3.png', plot = last_plot(),
       width = 5.5, height = 4, units = 'in')

```

```{r eval=FALSE}
rmarkdown::render('code/13_summary_fig.Rmd', output_file = '../docs/13_summary_fig.html')
```
