---
title: "nmds"
author: "Kate"
date: "November 29, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages & data}

# Load necessary packages
library(tidyverse)
library(vegan)

# Load necessary data
smamms <- read_csv('smamms.csv')
meta <- read_csv('sites.csv')
spp_info <- read_csv('species_info.csv')

```


```{r simplified data frames}

# Create severity dataframe
sevs <- meta %>% 
    mutate(
    severity = 
      case_when(
        severity == 'Green' ~ 'low',
        severity == 'Mixed' ~ 'med',
        severity == 'High' ~ 'high'
      )
  ) %>% 
  mutate(severity = factor(severity, levels = c('low', 'med', 'high'))) %>% 
  rename(site = site.code) %>% 
  arrange(severity) %>% 
  select(site, severity)

# Create combined and simplified data frame with only unique animals
smammeta <- full_join(smamms, sevs, by = 'site') %>% 
  filter(species != 'MISS' & species != 'SPRU') %>%
  group_by(indID) %>% 
  filter(row_number()==1) %>% # filter by unique animals
  ungroup() %>% 
  select(site, severity, species)

# Create species dataframe with shortened binomials
spp_names <- spp_info %>% 
  mutate(binomial_short = paste0(
    substring(binomial,1,1),
    ". ",
    gsub(".* ", '', binomial)
  )) %>% 
  select(species, family, common_name, binomial, binomial_short) %>% 
  semi_join(smammeta, by = 'species')

```


```{r species matrix, include=FALSE}

# Create a species matrix
matrix_temp <- smammeta %>% 
  group_by(site, species) %>% 
  tally() %>%  # count individuals per species per site
  spread(species, n) %>% # re-format into matrix
  ungroup() %>% 
  replace(., is.na(.), 0) # replace NAs with 0

sites <- matrix_temp$site # vector of just sites

matrix <- matrix_temp %>% 
  select(-site) # remove site column for input into vegan

matrix <- as.matrix(matrix)
rownames(matrix) <- sites

```


```{r nmds}

smamm_ord <- metaMDS(matrix,
                     distance = 'bray',
                     k = 2, # number of dimensions
                     trymax = 100) # how many times we want it to try a random start

colors <- c('darkgreen', 'orange', 'red')

par(mar = c(4,4,1,1))
plot(smamm_ord,
     display = 'sites',
     type = 'n')
points(smamm_ord,
       display = 'sites',
       cex = 1.5,
       pch = 19,
       col = colors[sevs$severity])
ordiellipse(smamm_ord,
            groups = sevs$severity, # by default plots ellipse with std error around centroids
            label = FALSE,
            col = colors,
            lwd = 2)

```



```{r ANOSIM}

# Compare species similarity across communities between fire severities using ANOSIM

smamm_dist <- matrix
attach(sevs)
smamm_ano <- anosim(smamm_dist, severity)
summary(smamm_ano)
plot(smamm_ano)

```

The community composition of small mammals differed significantly with fire severity (ANOSIM R = 0.222, p = 0.002).

STANDARDIZE: based on number of new animals per species per trap night
